In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('./data/aapl_us_d.csv', index_col=0)
df.iloc[:10]
df.iloc[2:10]
df.iloc[3:]
df.iloc[[1]]
df.iloc[[1, 4]]
df.iloc[: : 2]

            Otwarcie  Najwyzszy  Najnizszy  Zamkniecie    Wolumen
Data
2000-09-07    0.9040     0.9566     0.8907      0.9481  253966248
2000-09-11    0.8974     0.9232     0.8888      0.8937  218833639
2000-09-13    0.8678     0.9096     0.8678      0.8870  357343455
2000-09-15    0.8833     0.8897     0.8295      0.8443  460733679
2000-09-19    0.9136     0.9251     0.8956      0.9165  317083431
...              ...        ...        ...         ...        ...
2022-03-16  157.0500   160.0000   154.4600    159.5900  102300157
2022-03-18  160.5100   164.4800   159.7600    163.9800  123511692
2022-03-22  165.5100   169.4200   164.9100    168.8200   81532007
2022-03-24  171.0600   174.1400   170.2100    174.0700   90131418
2022-03-28  172.1700   175.7300   172.0000    175.6000   90371916

[2712 rows x 5 columns]

In [5]:
df.iloc[: , :2]
df.iloc[1:6, 1:2]

   Otwarcie
1    0.9422
2    0.8974
3    0.8768
4    0.8678
5    0.8956