In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10, 4),
                  columns=['one', 'two', 'three', 'four'])

for row in df.values:
    switch = np.random.choice([0, 1])
    if switch:
        i = np.random.choice([0, 1, 2, 3])
        row[i] = np.nan

In [3]:
df = df.fillna(0)

In [6]:
df['one'] = df['one'].fillna(0)

In [7]:
df.fillna(df.mean())

        one       two     three      four
0 -0.336880  1.491870 -0.860347 -1.779339
1  0.423104  1.533035 -0.274700  2.322198
2  0.000000 -1.550383  0.624454  0.583662
3  2.838346 -1.961829  0.163928 -0.613782
4  0.303358 -0.020030  1.783659 -0.006288
5  0.359440  0.046260 -0.129792 -0.779523
6  0.822575  0.046260 -1.199378  0.117094
7 -0.173158  0.046260 -0.019990  0.317896
8 -1.132061 -0.519180 -0.029246 -0.279010
9 -0.937748  1.350334  0.161793  0.054213

In [13]:
df.fillna(df.median())

        one       two     three      four
0 -0.778964  0.233582 -0.728200 -0.231725
1 -0.059079  0.585523  0.239922 -0.652225
2 -0.427071 -0.406403  0.382902 -0.999658
3 -0.666868  2.020533 -2.240770  1.246067
4 -0.059079  0.527165  1.424618 -0.491548
5 -0.069046  0.643880 -0.194490  0.907135
6  0.735319  0.345744 -0.383126 -0.468036
7  1.324050  1.845936 -0.893110 -0.231725
8  0.942753  0.585523 -2.314773  0.491124
9  0.019039  1.526745 -1.357734  0.680579

In [ ]:
df['four'] = df['four'].fillna(df['four'].mean)