In [2]:
import pandas as pd
import numpy as np

In [6]:
df1 = pd.DataFrame(np.random.rand(10, 4), columns=list('abcd'))
df2 = pd.DataFrame(np.random.rand(10, 4), columns=list('abcd'))
df3 = pd.DataFrame(np.random.rand(10, 4), columns=list('abcd'))
s = pd.Series(np.random.rand(10), name='x')

In [ ]:
# concat
# by rows
df = pd.concat([df1, df2, df3], ignore_index=True)
df_a = pd.concat([df1, df2, df3])
df_a.reset_index()

In [ ]:
# different column name
# by columns
df4 = pd.DataFrame(np.random.rand(10, 4), columns=list('abcd'))
df5 = pd.DataFrame(np.random.rand(10, 4), columns=list('efgh'))
df_b = pd.concat([df4, df5], axis=1)

In [20]:
#  outer, inner
df4 = df4[::2]
df6 = pd.concat([df4, df5], axis=1, join="outer")
df7 = pd.concat([df4, df5], axis=1, join="inner")
df6.reset_index()
df7.reset_index()

,index,a,b,c,d,e,f,g,h
0,0,0.859535,0.083489,0.55581,0.211069,0.911483,0.507497,0.802154,0.092196

In [24]:
# append Series to DataFrame
df8 = pd.concat([df3, s], axis=1)